// Stamp the canonical VERSION into every artifact's source.
//
//   VERSION ──►  esp32_matrix_webserver/version.h        (#define FW_VERSION)
//           ──►  esp32_matrix_webserver/data/version.json (served from LittleFS)
//           ──►  mcp_server/package.json                  ("version" field)
//
// Run directly (`node scripts/version-stamp.js`) or import `stamp()` for tests.
// Idempotent except for the version.json "stamped" timestamp, which always
// refreshes to record when the web bundle was last stamped.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { parseSemver } from "./version-lib.js";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const VERSION_H = `// GENERATED by scripts/version-stamp.js from /VERSION — do not edit by hand.
// Bump with \`npm run bump:patch|minor|major\`, then reflash to update the board.
#pragma once
#define FW_VERSION "%V%"
`;

/** Read and validate the canonical version from the VERSION file. */
export async function readVersion(root = REPO_ROOT) {
  const raw = await readFile(path.join(root, "VERSION"), "utf8");
  const version = raw.trim();
  parseSemver(version); // throws if malformed
  return version;
}

/** Write `version` into all three artifact sources under `root`. */
export async function stamp(version, root = REPO_ROOT) {
  parseSemver(version); // guard against stamping garbage

  // 1. Firmware header
  await writeFile(
    path.join(root, "esp32_matrix_webserver", "version.h"),
    VERSION_H.replace("%V%", version),
    "utf8",
  );

  // 2. Web bundle manifest (served from LittleFS)
  const webJson = JSON.stringify({ version, stamped: new Date().toISOString() }, null, 2) + "\n";
  await writeFile(
    path.join(root, "esp32_matrix_webserver", "data", "version.json"),
    webJson,
    "utf8",
  );

  // 3. MCP server manifest — read/modify/write to preserve the rest of the file
  const pkgPath = path.join(root, "mcp_server", "package.json");
  const pkg = JSON.parse(await readFile(pkgPath, "utf8"));
  pkg.version = version;
  await writeFile(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");

  return version;
}

// CLI entry: stamp the current VERSION into every artifact.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const version = await readVersion();
  await stamp(version);
  console.log(`Stamped v${version} → version.h, data/version.json, mcp_server/package.json`);
}
