// ============================================================
// ESP32-S3 Matrix Web Server Firmware
// Board: Waveshare ESP32-S3-Matrix (8x8 WS2812B)
// ============================================================
// PURPOSE:
//   This firmware turns the ESP32-S3 into a WiFi-connected 
//   HTTP server. It listens for commands sent from your PC
//   (via the MCP Node.js server) and controls the LED matrix.
//
//   Think of it this way:
//     [Claude] → [MCP Server on PC] → [HTTP] → [This firmware] → [LEDs]
//
// LIBRARIES — install via Arduino IDE → Tools → Manage Libraries:
//   - FastLED      by Daniel Garcia   (version 3.6 or later)
//   - ArduinoJson  by Benoit Blanchon (version 7.x)
//   - PNGdec       by Larry Bank      (any recent version) — for remote weather icon
//   - WiFiManager  by tzapu           (any recent version) — captive-portal WiFi setup
//   WiFi, WebServer, and WiFiClientSecure are built into the ESP32 Arduino core.
//
// ARDUINO IDE BOARD SETTINGS (Tools menu):
//   Board:            "ESP32S3 Dev Module"
//   USB Mode:         "Hardware CDC and JTAG"
//   USB CDC On Boot:  "Enabled"
//   Upload Speed:     921600
//   PSRAM:            "Enabled"  ← required: 2MB PSRAM keeps WiFi/web server stable under load
//   Flash Size:       "4MB (32Mb)"  ← board is 4MB, verified via esptool
//   Partition Scheme: "Huge APP (3MB No OTA / 1MB SPIFFS)"  ← LittleFS lives in the 1MB region
//
// UPLOADING WEB FILES (do this AFTER flashing firmware):
//   Arduino IDE → Tools → ESP32 LittleFS Data Upload
//
// FILE STRUCTURE — each .ino in this folder is compiled together:
//   esp32_matrix_webserver.ino — globals, setup(), loop(), core utilities
//   anim_fire.ino              — fire animation + spark system
//   anim_liquid.ino            — IMU driver + liquid/imu animations
//   anim_effects.ino           — rainbow, breathe, wave, solid
//   scroll_text.ino            — FONT data, drawCharCol, renderScrollFrame
//   weather.ino                — weather fetch, icon draw, chip temp
//   clock_timer.ino            — MINI_FONT, clock, all three timer modes
//   api_handlers.ino           — all HTTP route handler functions
// ============================================================

#include <WiFi.h>
#include <WiFiManager.h>
#include <ESPmDNS.h>
#include <WebServer.h>
#include <FastLED.h>
#include <ArduinoJson.h>
#include <LittleFS.h>
#include <Wire.h>
#include <math.h>
#include <HTTPClient.h>
#include <WiFiClientSecure.h>
#include <PNGdec.h>
#include <time.h>
#include <Preferences.h>   // NVS key/value store — used for auto-resume
#include <esp_wifi.h>      // esp_wifi_get_config — read stored SSID/password for explicit connect

// Optional hardcoded-WiFi override (diagnostic / escape hatch). Put in
// esp32_matrix_webserver/secrets.h (gitignored):
//   #define WIFI_SSID     "YourNetwork"
//   #define WIFI_PASSWORD "YourPassword"
// If defined, the firmware connects with these directly and NEVER touches the
// WiFiManager portal — useful to bypass portal credential handling entirely.
#if __has_include("secrets.h")
  #include "secrets.h"
#endif

// FW_VERSION — generated by scripts/version-stamp.js from the repo /VERSION.
// Reported by GET /api/status so we can tell which firmware is actually flashed.
#include "version.h"

#define SETTINGS_VERSION 1   // board settings schema version (see settings.ino)

// Version string read from the uploaded web bundle (data/version.json) at boot.
// Lets /api/status report firmware-vs-web drift in a single call. "unknown" =
// the LittleFS upload predates versioning (re-upload to start tracking).
String webVersion = "unknown";

// Presence Protocol: the last semantic status the board was told to show. Stored
// as already-normalized JSON (the MCP server validates before POSTing). Served
// verbatim at GET /api/presence for any renderer (the desktop card). RAM only —
// resets to idle on reboot. The LEDs are still driven by the MCP frame path in v0.
String presenceJson = "{\"intent\":\"idle\"}";

// ============================================================
// SECTION 1: HARDWARE CONFIGURATION
// ============================================================

#define LED_PIN    14
#define MATRIX_W   8
#define MATRIX_H   8
#define NUM_LEDS   (MATRIX_W * MATRIX_H)
#define LED_TYPE     WS2812B
#define COLOR_ORDER  RGB

#define IMU_SDA      11
#define IMU_SCL      12
#define QMI8658_ADDR 0x6B

// ============================================================
// SECTION 2: WIFI SETUP
// ============================================================
// WiFi credentials are configured at runtime via a captive portal —
// no hardcoded passwords, no recompiling. On first boot (or when saved
// credentials fail) the board starts a hotspot named "ESP32-Matrix-Setup".
// Connect to that network on any phone or laptop, enter your home WiFi
// name + password, and the board saves them to flash and reboots.
// From then on it connects automatically. To reconfigure, hold the BOOT
// button for 3 seconds while powering on (see setup() below).

// ============================================================
// SECTION 3: GLOBAL STATE
//
// All variables here are written by HTTP handlers and read by
// animation frame functions. Because the ESP32 is single-threaded
// (no RTOS tasks in this firmware), there are no race conditions —
// a handler runs to completion before loop() resumes.
// ============================================================

// FastLED LED buffer — one CRGB (24-bit RGB) per physical LED.
// FastLED stays registered to THIS buffer. matrixShow() backs it up to
// ledsBackup[], corrects it in place, shows, then restores — so the calibration
// correction reaches the panel but never compounds on read-back animations.
CRGB     leds[NUM_LEDS];

// ── LED calibration (Phase 3 correction layer) ───────────────
// Measured profile from data/calibration.json (Phase 2). Identity = do-nothing,
// so an absent/unparseable file never breaks rendering. See calibration.ino.
struct CalibrationProfile {
  uint8_t floorR = 1, floorG = 1, floorB = 1;        // min value a nonzero channel is lifted to
  float   gainR = 1.0f, gainG = 1.0f, gainB = 1.0f;  // white-balance gains (<=1.0, never amplify)
  float   gamma = 1.0f;                               // perceptual exponent for ramps
};
CalibrationProfile calib;          // populated by loadCalibration() at boot
uint8_t  gammaLUT[256];            // gammaLUT[v] = round(255*(v/255)^calib.gamma)
CRGB     ledsBackup[NUM_LEDS];     // matrixShow() stashes the uncorrected leds[] here, then restores

// Phase 3 correction pipeline (bodies in calibration.ino). Declared here in the
// main ino so every later-concatenated .ino resolves them regardless of order.
void loadCalibration();
void buildGammaLUT();
void applyCalibration(CRGB* buf);
void matrixShow();

// Built-in Arduino WebServer — handles HTTP on port 80.
WebServer server(80);

// NVS (non-volatile storage) — remembers the last display + brightness so the
// board resumes itself after a power cycle (see setup() and the API handlers).
Preferences prefs;
// Auto-resume writes are DEBOUNCED: handlers set these + a dirty flag, and loop()
// flushes once things settle. This avoids churning the NVS partition that also
// holds the WiFi credentials (rapid writes there can cost you your WiFi).
String   resumeKind    = "";
String   resumeBody    = "";
bool     resumeDirty   = false;
uint32_t resumeDirtyMs = 0;
// Set by applyAnimationBody() from the body's "transient" flag, so handleAnimation
// can honor it WITHOUT re-parsing the body a second time (the old double-parse
// doubled per-request JSON allocation — a contributor to heap pressure under rapid
// POSTs). Only handleAnimation reads it; the boot-resume/idle callers ignore it.
bool     launchWasTransient = false;
// The brightness value that persists to NVS. Tracked separately from the live
// `brightness` global so diagnostics that drive the panel hard (grid-test defaults
// to 255 for calibration) can never be what the board boots back into — at 255
// an all-lit panel pulls ~3-4A and can brown out USB power (see PITFALLS).
uint8_t  resumeBri     = 40;

// ── Board settings (NVS-backed) ──────────────────────────────
// The struct + global live HERE in the main ino (not settings.ino) so they are
// visible to setup() and every later-concatenated .ino. The load/save/json logic
// lives in settings.ino. There is deliberately NO "default brightness" field — it
// is unified with the live/auto-resume brightness (the NVS "bri" key).
struct Settings {
  bool     idleOn;        // master switch for the screensaver engine
  String   idleApps;      // CSV of enabled screensaver type names
  uint32_t idleAfterS;    // seconds of board silence before screensaver starts
  uint32_t idleRotS;      // seconds between screensaver re-picks
  uint8_t  idleBri;       // brightness during the screensaver
  String   bootAnim;      // pinned boot animation type ("" = auto-resume)
  String   tz;            // POSIX TZ for the clock ("" = none)
  bool     calibCorrection; // apply the measured LED calibration correction (default true)
};
Settings settings;

// ── Animation control ────────────────────────────────────────
uint8_t  brightness      = 40;      // global FastLED brightness (0-255)
bool     animationActive = false;   // true while any animation is running
String   animationName   = "";      // which animation is active (e.g. "fire")
uint32_t animationSpeed  = 66;      // ms between frames (lower = faster)
uint32_t lastFrameMs     = 0;       // millis() timestamp of the last frame
CRGB     solidColor      = CRGB(0, 100, 255);   // color used by solid/breathe/wave

// ── Text scroll state ────────────────────────────────────────
bool     textActive         = false;
String   scrollText         = "";
CRGB     scrollColor        = CRGB::White;
CRGB     scrollColor2       = CRGB(255,  68,   0);   // gradient colors 2-4
CRGB     scrollColor3       = CRGB(  0, 204, 100);
CRGB     scrollColor4       = CRGB(  0, 100, 255);
bool     scrollGradient     = false;
bool     scrollSmall        = false;               // use 3×5 font
bool     scrollTiny         = false;               // use 3×3 font (overrides small)
bool     scrollPausing      = false;               // true during the 1s gap between loops
uint32_t scrollPauseUntilMs = 0;
uint32_t scrollSpeed        = 100;   // ms per scroll step (lower = faster)
uint32_t lastScrollMs       = 0;
int      scrollOffset       = 0;     // how many pixels the text strip has advanced
int      scrollPixelLen     = 0;     // total pixel width of the text string

// Per-font character stride (char width + 1px gap between chars)
#define CHAR_W          5
#define CHAR_GAP        1
#define CHAR_TOTAL      (CHAR_W + CHAR_GAP)   // = 6 pixels per normal char

#define SMALL_CHAR_W     3
#define SMALL_CHAR_TOTAL 4   // 3 wide + 1 gap
#define TINY_CHAR_TOTAL  4   // 3×3 font: same stride as small

// ── Chip temperature ─────────────────────────────────────────
String   chipTempUnit      = "F";   // "F" or "C"

// ── Weather state ─────────────────────────────────────────────
String   weatherZip        = "85013";   // US zip code
String   weatherUnit       = "F";       // temperature unit: "F" or "C"
int      weatherTempVal    = 0;         // last fetched temperature
int      weatherCode       = 113;       // wttr.in condition code (113 = clear)
int      weatherHumidity   = 0;         // percent
int      weatherUvIndex    = 0;
int      weatherPressure   = 0;         // hPa
uint32_t lastWeatherFetch  = 0;         // millis() of last fetch ATTEMPT (success or failure)
bool     weatherNeedsFetch = false;     // handler sets this; loop() does the fetch (off the request/boot path)
bool     weatherFetchOk    = false;     // true once a fetch has succeeded; until then retry every 30s, not 10 min
uint8_t  weatherFrame      = 0;         // frame counter for icon animations
String   weatherDataMode   = "temp";    // which data to show: temp/humidity/uv/pressure/cycle
String   weatherIconSource = "animated";// "animated" (built-in) or "remote" (fetched PNG)
uint32_t weatherPhaseStart = 0;         // millis() when the current phase (data/icon) started
bool     weatherShowIcon   = false;     // true = showing icon, false = showing data
CRGB     weatherIconBuf[64];            // decoded remote PNG icon, scaled to 8×8
bool     weatherHasIcon    = false;     // true once the remote icon has been fetched

// ── Weather 2 state ───────────────────────────────────────────
String   weather2Unit    = "F";
CRGB     weather2Color1  = CRGB(255, 165,   0);  // temp tens digit (amber)
CRGB     weather2Color2  = CRGB(255, 220,  80);  // temp units digit (gold)
int      weatherTempF    = 0;   // raw °F — stored separately so W1/W2 can use independent units
int      weatherTempC    = 0;   // raw °C

// ── Clock state ───────────────────────────────────────────────
CRGB     clockColorHours = CRGB(255,  51,   0);  // hours digit color    (#FF3300)
CRGB     clockColorColon = CRGB(255, 255, 255);  // colon dot color      (#FFFFFF)
CRGB     clockColorMins  = CRGB(  0, 204, 255);  // minutes digit color  (#00CCFF)
int      clockTimezone   = -7;                   // UTC offset in hours (e.g. -7 = Arizona MST)
String   clockTZ         = "";                    // POSIX TZ string (DST-aware, e.g. "MST7MDT,M3.2.0,M11.1.0"); empty = use offset
bool     ntpSynced       = false;
int      clockPrevHour   = -1;                   // used to skip redraws when nothing changed
int      clockPrevMin    = -1;

// ── Timer state ───────────────────────────────────────────────
uint32_t timerEndMs        = 0;             // millis() when the timer expires
uint32_t timerTotalMs      = 0;             // original duration in ms
CRGB     timerColor1       = CRGB(255, 200, 0);   // start color (bottom of fill, minutes)
CRGB     timerColor2       = CRGB(255,   0, 0);   // end color (top of fill, seconds)
CRGB     timerColorColon   = CRGB::White;          // colon color (timer_text only)
int      timerExpiredState = 0;             // 0=running, 1=blinking, 2=solid (expired)
uint32_t timerExpiredMs    = 0;

// ── Snow timer state ──────────────────────────────────────────
// SnowCell: one LED position. row 0 = bottom, row 7 = top.
// (The Y coordinate is inverted from matrix coordinates where y=0 is top.)
struct SnowCell { uint8_t col; uint8_t row; };
SnowCell snowPos[64];            // settlement order: cells sorted bottom-to-top, shuffled within each row
int      snowSettledCount   = 0; // how many cells have settled so far
bool     snowFallActive     = false;
int      snowFallCol        = 0;
int      snowFallTargetY    = 7;
uint32_t snowFallStartMs    = 0;
uint32_t snowFallDurationMs = 500;

// ── Liquid/IMU state ──────────────────────────────────────────
// Liquid is a 2D closed-container model: gravity is a vector in the matrix
// plane, and the fluid fills the most "downhill" cells up to a threshold that
// sloshes with momentum. (See docs/superpowers/specs/2026-06-08-liquid-fixes-design.md)
bool    imuReady              = false;         // set to true if IMU is detected at boot
float   liquidLevel           = 0.0f;          // fill threshold along the gravity axis
float   liquidLevelVel        = 0.0f;          // slosh velocity of that threshold
float   liquidGX              = 0.0f;          // smoothed in-plane gravity direction (x)
float   liquidGY              = 1.0f;          // smoothed in-plane gravity direction (y)
float   liquidDamping         = 0.88f;         // energy loss per frame (set from viscosity param)
bool    liquidGradient        = false;         // true = custom top/bottom gradient instead of palette
CRGB    liquidTopColor        = CRGB(230, 250, 255);  // surface/froth color (custom mode)
CRGB    liquidBottomColor     = CRGB(  0,  40, 160);  // deep color (custom mode)

// ── Calendar state ────────────────────────────────────────────
// Styles: "scroll" (date scrolls), "bignum" (day), "grid" (month grid), "clock"
// (month over day, clock-style). Date comes from NTP, same as clock mode.
String  calendarStyle  = "scroll";   // default matches the Calendar web page's selected style
CRGB    calendarColor1 = CRGB(0, 200, 255);    // primary  (day / today / text)
CRGB    calendarColor2 = CRGB(255, 120, 0);    // secondary(month / other days)
CRGB    calendarColor3 = CRGB(80, 80, 90);     // accent   (separator / grid frame)
int     calendarScrollX = MATRIX_W;            // scroll position for "scroll" style
uint32_t calendarScrollMs = 80;                // ms per 1px scroll advance (set from the page's speed slider)
bool    calendarScrollMono = false;            // scroll: true = whole date in color1; false = weekday/month/day in color1/2/3

// ── Frames player (Claude's expression channel) ───────────────
// Plays a short uploaded frame sequence — the transport for the MCP server's
// expression tools (canned glyphs, Claude-drawn animations). See
// docs/superpowers/specs/2026-06-11-claude-expression-display.md.
#define MAX_PLAY_FRAMES 24
CRGB     framesBuf[MAX_PLAY_FRAMES * 64];   // 24 frames × 64 px ≈ 4.6KB static
uint8_t  framesCount  = 0;    // frames loaded
uint16_t framesLoops  = 0;    // 0 = loop forever; N = play N passes then HOLD the last frame
uint16_t framesPlayed = 0;    // completed passes
uint8_t  framesIdx    = 0;    // next frame to show

// ── Sound (vibration) visualizer state ────────────────────────
// No microphone — the IMU feels low-frequency vibration (bass through a surface).
CRGB    soundColor1     = CRGB(0, 80, 255);     // bottom of the VU bar
CRGB    soundColor2     = CRGB(255, 0, 160);    // top of the VU bar
float   soundSensitivity = 5.0f;                // 0-10
float   soundBaseline   = 1.0f;                 // slow-tracked steady magnitude (gravity)
float   soundEnergy     = 0.0f;                 // smoothed current level 0-1
float   soundPeak       = 0.0f;                 // decaying peak marker 0-1

// ── Gradient Spiral ───────────────────────────────────────────────────────────
CRGB     spiralColor1   = CRGB(255,   0,   0);
CRGB     spiralColor2   = CRGB(  0,   0, 255);

// ── Gradient Starfield ────────────────────────────────────────────────────────
CRGB     starColor1     = CRGB(255, 255, 255);
CRGB     starColor2     = CRGB(  0, 100, 255);
uint8_t  starDensity    = 8;
bool     starInward     = false;

// ── Dance Floor ───────────────────────────────────────────────────────────────
uint8_t  dfPalette  =  0;
uint8_t  dfHoldMin  = 12;

// ── Fireworks 1 ───────────────────────────────────────────────────────────────
CRGB     fwColor1       = CRGB(255,  50,   0);
CRGB     fwColor2       = CRGB(255, 200,   0);
CRGB     fwColor3       = CRGB(  0, 100, 255);

// ── Fireworks 2 ───────────────────────────────────────────────────────────────
CRGB     fw2Color1      = CRGB(255,  50,   0);
CRGB     fw2Color2      = CRGB(255, 200,   0);
CRGB     fw2Color3      = CRGB(  0, 100, 255);

// ── Wave ──────────────────────────────────────────────────────────────────────
CRGB     waveColor1     = CRGB(  0,   0, 255);   // surface color
CRGB     waveColor2     = CRGB(  0,   0,  40);   // depth color

// ── Rainbow ───────────────────────────────────────────────────────────────────
bool  rainbowUsePalette   = false;
CRGB  rainbowPalColors[4] = { CRGB(255,0,0), CRGB(255,200,0), CRGB(0,200,0), CRGB(0,100,255) };

// ── Comet ─────────────────────────────────────────────────────────────────────
// cometColor3 bumped to R=200 — at nscale8(64) and bri=40 gives effective=8 (was borderline 6)
CRGB     cometColor1    = CRGB(255, 200,  50);
CRGB     cometColor2    = CRGB(255, 100,   0);
CRGB     cometColor3    = CRGB(200,  50,   0);
CRGB     cometColor4    = CRGB( 80,  10,   0);

// ── Claudesweep ───────────────────────────────────────────────────────────────
CRGB     sweepColor     = CRGB(0xFF, 0xB0, 0x00);   // claudesweep border hue (amber CRT default)

// ── Sun ───────────────────────────────────────────────────────────────────────
CRGB     sunColor1      = CRGB(255, 183,   0);
CRGB     sunColor2      = CRGB(255, 102,   0);
CRGB     sunColor3      = CRGB(255,  51,   0);
CRGB     sunColor4      = CRGB(204,  17,   0);
CRGB     sunColor5      = CRGB(136,   0,   0);
uint8_t  sunDiscBri     = 200;   // disc brightness 0-255
uint8_t  sunRingBri     = 200;   // orbit dot brightness 0-255

// ── Frostbite ─────────────────────────────────────────────────────────────────
CRGB     fbColor     = CRGB(220, 230, 255);   // cool ice-white default
uint8_t  fbSparkRate = 20;                    // sparkle spawn probability 0-100
uint8_t  fbMistMax   = 80;                    // shimmer brightness ceiling 0-255

// ── Grid Test ─────────────────────────────────────────────────────────────────
// Diagnostic app for establishing per-pixel color/brightness thresholds.
// "color" mode: 64 pixels with R = (linear index + 1) * 4 (R=4 at [1,1] → R=255 at [8,8])
// "brightness" mode: all pixels at full red (255,0,0), vary brightness to find cutoff.
// Static display — no animation loop; leds[] is redrawn only when the endpoint is called.
String  gridTestMode       = "color";   // "color" or "brightness"
uint8_t gridTestBrightness = 255;

// ============================================================
// SECTION 5: LED BRIGHTNESS CALIBRATION REFERENCE
//
// Established via grid test on 2026-05-27. Confirmed empirically
// against this specific Waveshare ESP32-S3-Matrix board.
//
// ── FORMULA ──────────────────────────────────────────────────
//   FastLED's nscale8x3 (used internally by FastLED.setBrightness)
//   applies the following to every channel before writing to the strip:
//
//       effective = (channel × (brightness + 1)) >> 8
//
//   The LED is physically ON  when effective >= 1.
//   The LED is physically OFF when effective == 0.
//
// ── MINIMUM VISIBLE CHANNEL VALUE ────────────────────────────
//   min_visible = ceil(256 / (brightness + 1))
//
//   brightness = 255 → min = 1    (anything non-zero is visible)
//   brightness = 100 → min = 3
//   brightness =  40 → min = 7
//   brightness =  20 → min = 13
//   brightness =  10 → min = 24
//   brightness =   5 → min = 43
//   brightness =   3 → min = 64
//
//   Any channel (R, G, or B) below min_visible is physically dark
//   regardless of what color you set.
//
// ── DESIGN RULES FOR APP DEVELOPMENT ────────────────────────
//   1. Before using a color in an app, verify every channel
//      satisfies: channel × (brightness + 1) >= 256.
//      If not, that channel contributes nothing to the output.
//
//   2. For gradient/fade effects (trails, halos, backgrounds):
//      The dimmest step MUST still clear the threshold.
//      e.g. a 5-step trail at bri=40 whose dimmest step = 20:
//        20 × 41 / 256 = 3.2 → 3.  OK (visible), but barely.
//      At bri=10 the same step: 20 × 11 / 256 = 0.86 → 0. GONE.
//
//   3. Subtle color differences (e.g. R=50 vs R=60) may be
//      indistinguishable at low brightness because both map to
//      the same small effective integer.
//
//   4. In JS previews, use this exact formula:
//         Math.floor(channel * (brightness + 1) / 256)
//      NOT  channel * brightness / 255  — that formula is wrong
//      and was the reason previews did not match the board.
//
// ── BRIGHTNESS SWEEP OBSERVATIONS ────────────────────────────
//   brightness = 0  → all LEDs off (FastLED special-cases 0).
//   brightness = 1  → full red (255,0,0) barely visible; effective = 1.
//   brightness 1→255 → visibly and smoothly increases.
//
// ── RELIABILITY NOTE ─────────────────────────────────────────
//   The formula is reliable for brightness >= 3. At brightness 1-2,
//   individual LED variation on this board makes the threshold
//   slightly inconsistent from pixel to pixel. Design for >= 3.
// ============================================================

// ============================================================
// SECTION 4: COORDINATE MAPPING
//
// The Waveshare ESP32-S3-Matrix wires its 8×8 WS2812B grid in
// a simple raster layout — every row goes left-to-right, top
// row first. So LED 0 = top-left, LED 7 = top-right,
// LED 8 = start of row 1, LED 63 = bottom-right.
//
// x=0 is left, x=7 is right. y=0 is top, y=7 is bottom.
// ============================================================

// Converts (x, y) matrix coordinates to a flat leds[] index.
// Returns -1 for any out-of-bounds coordinate — callers check for this.
int XY(int x, int y) {
  if (x < 0 || x >= MATRIX_W || y < 0 || y >= MATRIX_H) return -1;
  return y * MATRIX_W + x;
}

// Safe pixel setter: does nothing if coordinates are out of bounds.
void setPixel(int x, int y, CRGB color) {
  int idx = XY(x, y);
  if (idx >= 0) leds[idx] = color;
}

// Parses a CSS hex color string ("#RRGGBB") into a CRGB value.
// strtol(..., 16) converts the 6-char hex string to a 24-bit integer,
// then bit-masking extracts each 8-bit channel.
// Returns white if the input format is invalid.
CRGB hexToColor(String hex) {
  if (hex.startsWith("#")) hex = hex.substring(1);
  if (hex.length() != 6) return CRGB::White;
  long v = strtol(hex.c_str(), nullptr, 16);
  return CRGB((v >> 16) & 0xFF, (v >> 8) & 0xFF, v & 0xFF);
}

// ============================================================
// SECTION 9: HTTP HELPERS
// ============================================================

void sendJson(int code, const String& body) {
  server.send(code, "application/json", body);
}

String getContentType(String path) {
  if (path.endsWith(".html")) return "text/html";
  if (path.endsWith(".css"))  return "text/css";
  if (path.endsWith(".js"))   return "application/javascript";
  if (path.endsWith(".json")) return "application/json";
  if (path.endsWith(".png"))  return "image/png";
  if (path.endsWith(".jpg") || path.endsWith(".jpeg")) return "image/jpeg";
  if (path.endsWith(".svg"))  return "image/svg+xml";
  if (path.endsWith(".ico"))  return "image/x-icon";
  return "text/plain";
}

void stopAll() {
  animationActive = false;
  textActive = false;
}

// ============================================================
// SECTION 10: HTTP ROUTE HANDLERS (continued in api_handlers.ino)
// ============================================================

void handleRoot() {
  if (LittleFS.exists("/index.html")) {
    File file = LittleFS.open("/index.html", "r");
    server.streamFile(file, "text/html");
    file.close();
    return;
  }
  String ip = WiFi.localIP().toString();
  String html = "<!DOCTYPE html><html><body style='font-family:monospace;padding:20px;background:#111;color:#eee'>";
  html += "<h2 style='color:#f90'>ESP32-S3 Matrix — Firmware OK, web files not uploaded yet</h2>";
  html += "<p>Board is running at <strong>" + ip + "</strong>. The API is ready.</p>";
  html += "<p style='margin-top:12px'>To load the web UI, upload the <code>data/</code> folder:<br>";
  html += "<strong>Arduino IDE &rarr; Tools &rarr; ESP32 LittleFS Data Upload</strong></p>";
  html += "<h3 style='margin-top:20px'>API Endpoints</h3><pre style='background:#222;padding:16px;border-radius:6px'>";
  html += "POST /api/display/clear\n";
  html += "POST /api/brightness          {\"level\": 0-255}\n";
  html += "POST /api/display/text        {\"text\": \"HELLO\", \"color\": \"#FF0000\", \"scroll_speed\": 100}\n";
  html += "POST /api/display/animation   {\"type\": \"fire|rainbow|breathe|wave|solid\",\n";
  html += "                               \"speed\": 66, \"theme\": \"classic|blue|green|purple\",\n";
  html += "                               \"intensity\": 1-10, \"tendrils\": 0-10}\n";
  html += "POST /api/display/matrix      {\"matrix\": [[8 rows of 8 hex colors]]}\n";
  html += "POST /api/display/temperature {\"value\": 72, \"unit\": \"F\", \"color\": \"#FF4400\"}\n";
  html += "GET  /api/sensors/temperature\n";
  html += "</pre></body></html>";
  server.send(200, "text/html", html);
}

// ============================================================
// SECTION 11: SETUP — runs once on boot
// ============================================================

bool applyAnimationBody(const String& body);   // defined in api_handlers.ino (used by auto-resume)

// Human-readable WiFi auth mode — tells us if a network is plain WPA2 or the
// WPA2/WPA3 transition mode that some ESP32 cores fail to handshake with.
static const char* encName(wifi_auth_mode_t m) {
  switch (m) {
    case WIFI_AUTH_OPEN:          return "open";
    case WIFI_AUTH_WEP:           return "WEP";
    case WIFI_AUTH_WPA_PSK:       return "WPA";
    case WIFI_AUTH_WPA2_PSK:      return "WPA2";
    case WIFI_AUTH_WPA_WPA2_PSK:  return "WPA/WPA2";
    case WIFI_AUTH_WPA3_PSK:      return "WPA3";
    case WIFI_AUTH_WPA2_WPA3_PSK: return "WPA2/WPA3-transition";
    default:                      return "other";
  }
}

// Diagnostic pre-connect scan: print every visible network's signal strength,
// channel, and auth mode. Answers "is the signal weak?" and "is the router in
// WPA3-transition mode?" directly from the board's point of view.
static void scanReport() {
  Serial.println("Scanning...");
  int n = WiFi.scanNetworks();
  for (int i = 0; i < n; i++) {
    Serial.printf("  '%s'  bssid=%s  ch=%d  rssi=%d dBm  auth=%s\n",
                  WiFi.SSID(i).c_str(), WiFi.BSSIDstr(i).c_str(),
                  WiFi.channel(i), WiFi.RSSI(i),
                  encName(WiFi.encryptionType(i)));
  }
  WiFi.scanDelete();
}

// Wait up to timeoutMs for WiFi to come up, pulsing blue and logging the live
// status code every 2s so connect problems are visible in the Serial Monitor.
static void waitForWiFiConnect(uint32_t timeoutMs) {
  uint32_t start = millis(), lastStat = 0;
  // WiFi.begin() has run, so the driver is up and this readback is authoritative —
  // unlike the boot-time "STA MAC" print, which can race the 3.x async driver and
  // show zeros. This is the MAC the router actually sees (incl. WIFI_MAC_OVERRIDE),
  // and it prints even when the connect FAILS — the case where it matters most.
  Serial.print("  presenting MAC: "); Serial.println(WiFi.macAddress());
  while (WiFi.status() != WL_CONNECTED && millis() - start < timeoutMs) {
    if (millis() - lastStat >= 2000) {
      lastStat = millis();
      Serial.printf("  connecting... status=%d\n", (int)WiFi.status());
    }
    bool on = ((millis() - start) / 400) % 2;   // pulse blue while connecting
    fill_solid(leds, NUM_LEDS, on ? CRGB::Blue : CRGB::Black);
    FastLED.show();
    delay(200);
  }
}

void setup() {
  Serial.begin(115200);
#if ARDUINO_USB_CDC_ON_BOOT && ARDUINO_USB_MODE
  // Serial is the hardware USB-CDC port (USB CDC On Boot: Enabled). CRITICAL:
  // with the cable plugged in but no terminal draining (Serial Monitor closed —
  // the normal state), HWCDC::write blocks up to tx_timeout_ms per chunk and
  // tolerates 20 consecutive timeouts — ~2 SECONDS of frozen loop per print.
  // The 10s heap log alone made every animation hitch and the web server crawl.
  // Timeout 0 = never block: prints flow when a monitor is attached, drop when
  // it isn't. Diagnostics are best-effort; the display and server are not.
  Serial.setTxTimeoutMs(0);
#endif
  delay(500);
  Serial.println("\n=== ESP32-S3 Matrix Web Server ===");

  prefs.begin("matrix", false);   // open NVS (read/write) for auto-resume state

  initIMU();

  FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS);
  FastLED.setBrightness(brightness);
  fill_solid(leds, NUM_LEDS, CRGB::Black);
  FastLED.show();
  Serial.println("LEDs initialized.");

  // Hold BOOT (GPIO 0) during power-on to wipe saved credentials and force
  // the config portal — useful if you're moving the board to a new network.
  pinMode(0, INPUT_PULLUP);
  delay(10);
  if (digitalRead(0) == LOW) {
    // Require a sustained ~1s hold. A single glitchy strapping-pin read right
    // after a USB flash/reset must NOT wipe WiFi credentials by accident.
    delay(1000);
    if (digitalRead(0) == LOW) {
      Serial.println("BOOT held 1s — clearing saved WiFi credentials.");
      WiFiManager wm;
      wm.resetSettings();
    } else {
      Serial.println("BOOT was only a blip — keeping saved WiFi credentials.");
    }
  }

  // WiFi event handlers, registered up front so they catch the initial connect
  // too: log disconnect reasons, and (re)announce mDNS on every got-IP.
  WiFi.onEvent([](WiFiEvent_t, WiFiEventInfo_t info) {
    Serial.printf("WiFi DISCONNECTED, reason=%d\n", info.wifi_sta_disconnected.reason);
  }, ARDUINO_EVENT_WIFI_STA_DISCONNECTED);
  WiFi.onEvent([](WiFiEvent_t, WiFiEventInfo_t) {
    Serial.print("WiFi got IP "); Serial.println(WiFi.localIP());
    MDNS.end(); MDNS.begin("esp32matrix");
  }, ARDUINO_EVENT_WIFI_STA_GOT_IP);

  // Diagnostic: PSRAM state. If Tools says Enabled but this prints "NOT active",
  // PSRAM init failed at early boot — which can also wedge WiFi driver init.
  Serial.printf("PSRAM: %s (size=%u bytes)\n", psramFound() ? "active" : "NOT active", ESP.getPsramSize());

  WiFi.mode(WIFI_STA);   // init the WiFi driver so the stored config is readable

  // Core 3.x brings the driver up asynchronously — wait until it can report a
  // MAC before touching it (calling esp_wifi_set_mac too early fails silently
  // and reads back 00:00:00:00:00:00).
  {
    uint8_t cur[6] = {0};
    uint32_t t0 = millis();
    while (esp_wifi_get_mac(WIFI_IF_STA, cur) != ESP_OK && millis() - t0 < 3000) delay(20);
  }

#ifdef WIFI_MAC_OVERRIDE
  // Present a different MAC to the network — escape hatch for a router/mesh
  // that has auto-blocklisted the board's real MAC (it can't be unblocked on
  // routers with no accessible device list). Must run before any connect/scan.
  {
    uint8_t newMac[6] = WIFI_MAC_OVERRIDE;
    esp_err_t macErr = esp_wifi_set_mac(WIFI_IF_STA, newMac);
    if (macErr != ESP_OK) {
      // Some driver states only allow a MAC change while stopped: stop→set→start.
      esp_wifi_stop();
      delay(100);
      macErr = esp_wifi_set_mac(WIFI_IF_STA, newMac);
      esp_wifi_start();
      delay(100);
    }
    Serial.printf("MAC override %s (err=%d)\n", macErr == ESP_OK ? "applied" : "FAILED", (int)macErr);
  }
#endif
  // All-zeros here = the async driver wasn't up yet at read time; the
  // authoritative value is the "presenting MAC" line during the connect wait.
  Serial.print("STA MAC: "); Serial.println(WiFi.macAddress());

  scanReport();          // diagnostic: signal strength + auth mode of every visible network

#ifdef WIFI_SSID
  // Hardcoded override from secrets.h — bypasses the portal and its credential
  // handling entirely. Connect and keep retrying; never open the portal.
  Serial.println("secrets.h credentials found — connecting directly (portal bypassed).");
  WiFi.setAutoReconnect(true);
  WiFi.setSleep(false);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  waitForWiFiConnect(25000);
  if (WiFi.status() != WL_CONNECTED)
    Serial.println("Hardcoded WiFi not up yet — running anyway; watchdog keeps retrying.");
#else
  WiFiManager wm;
  if (wm.getWiFiIsSaved()) {
    // We HAVE saved WiFi credentials → connect to that network and KEEP TRYING.
    // Do NOT fall into the blocking config portal on a slow/transient connect:
    // the board keeps running (auto-resumed display) and the loop() watchdog +
    // auto-reconnect keep retrying the saved network until it comes back. The
    // portal is ONLY for a never-configured board or a deliberately held BOOT.
    wifi_config_t conf;
    memset(&conf, 0, sizeof(conf));
    esp_wifi_get_config(WIFI_IF_STA, &conf);
    Serial.printf("Saved WiFi found — SSID '%s' — connecting (no portal; will keep retrying)...\n",
                  (const char*)conf.sta.ssid);
    WiFi.setAutoReconnect(true);
    WiFi.setSleep(false);   // disable modem power-save (a common silent-drop cause)
    // Explicit-credential begin: WiFi.begin() with no args showed it can silently
    // start no attempt (no disconnect events at all). Passing the stored
    // SSID/password removes that ambiguity.
    WiFi.begin((const char*)conf.sta.ssid, (const char*)conf.sta.password);
    waitForWiFiConnect(25000);
    if (WiFi.status() != WL_CONNECTED)
      Serial.println("Saved WiFi not up yet — running anyway; watchdog keeps retrying in the background.");
  } else {
    // No saved credentials → first-time setup only: open the config portal.
    Serial.println("No saved WiFi — opening setup portal 'ESP32-Matrix-Setup' (192.168.4.1).");
    fill_solid(leds, NUM_LEDS, CRGB(255, 80, 0));   // amber = portal
    FastLED.show();
    wm.setAPCallback([](WiFiManager*) {
      fill_solid(leds, NUM_LEDS, CRGB(255, 80, 0));
      FastLED.show();
    });
    wm.startConfigPortal("ESP32-Matrix-Setup");
    WiFi.setAutoReconnect(true);
    WiFi.setSleep(false);
  }
#endif  // WIFI_SSID

  if (WiFi.status() == WL_CONNECTED) {
    Serial.println("WiFi connected!");
    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());
    Serial.print("MAC presented: ");
    Serial.println(WiFi.macAddress());
    fill_solid(leds, NUM_LEDS, CRGB::Green);   // brief green = connected OK
    FastLED.show();
    delay(600);
  }
  fill_solid(leds, NUM_LEDS, CRGB::Black);
  FastLED.show();

  if (!LittleFS.begin(true)) {
    Serial.println("WARNING: LittleFS mount failed — web UI files not available yet.");
    Serial.println("  Upload data/ folder via: Tools → ESP32 LittleFS Data Upload");
  } else if (WiFi.status() == WL_CONNECTED) {
    Serial.println("LittleFS mounted. Web UI ready at http://" + WiFi.localIP().toString());
  } else {
    Serial.println("LittleFS mounted. Web UI will be ready once WiFi connects.");
  }

  // Read the web bundle's stamped version once at boot (web files never change
  // at runtime). /api/status reports this as web_version so a single status
  // call reveals whether the flash and the LittleFS upload are in sync.
  if (LittleFS.exists("/version.json")) {
    File vf = LittleFS.open("/version.json", "r");
    JsonDocument vdoc;
    if (deserializeJson(vdoc, vf) == DeserializationError::Ok && vdoc["version"].is<const char*>())
      webVersion = String((const char*)vdoc["version"]);
    vf.close();
  }
  Serial.println("Firmware v" FW_VERSION " (built " __DATE__ " " __TIME__ "), web bundle v" + webVersion);

  loadCalibration();   // calibration.ino — measured profile into `calib` + gammaLUT (identity if absent)

  server.on("/",                          HTTP_GET,  handleRoot);
  server.on("/api/display/clear",         HTTP_POST, handleClear);
  server.on("/api/brightness",            HTTP_POST, handleBrightness);
  server.on("/api/display/text",          HTTP_POST, handleText);
  server.on("/api/display/animation",     HTTP_POST, handleAnimation);
  server.on("/api/display/matrix",        HTTP_POST, handleMatrix);
  server.on("/api/display/frames",        HTTP_POST, handleFrames);
  server.on("/api/display/framebuffer",   HTTP_GET,  handleFramebuffer);
  server.on("/api/display/temperature",   HTTP_POST, handleTemperature);
  server.on("/api/sensors/temperature",   HTTP_GET,  handleSensorTemperature);
  server.on("/api/sensors/accelerometer", HTTP_GET,  handleSensorAccelerometer);
  server.on("/api/sensors/weather",       HTTP_GET,  handleSensorWeather);
  server.on("/api/weather/mode",          HTTP_POST, handleWeatherMode);
  server.on("/api/status",               HTTP_GET,  handleStatus);
  server.on("/api/presence",             HTTP_GET,  handlePresenceGet);
  server.on("/api/presence",             HTTP_POST, handlePresencePost);
  server.on("/api/grid-test/set",        HTTP_POST, handleGridTest);
  server.on("/api/calibration",          HTTP_GET,  handleCalibrationGet);
  server.on("/api/calibration",          HTTP_POST, handleCalibrationPost);
  server.on("/api/settings",              HTTP_GET,  handleSettingsGet);
  server.on("/api/settings",              HTTP_POST, handleSettingsPost);
  server.on("/api/idle/arm",              HTTP_POST, handleIdleArm);
  server.onNotFound([]() {
    String path = server.uri();
    if (LittleFS.exists(path)) {
      File file = LittleFS.open(path, "r");
      // Let the browser cache the shared static assets (bright.js / palette.js /
      // ledsim.js / images) — every page pulls them, and re-serving each one is
      // a full TCP connection on a single-client server (WebServer pins to one
      // connection at a time; an idle browser socket can hold it for up to 5s,
      // see HTTP_MAX_DATA_WAIT). HTML deliberately stays uncached so LittleFS
      // uploads show up on plain reload. ⚠ After re-uploading a CHANGED .js,
      // hard-refresh (Ctrl+F5) once — see PITFALLS.
      if (path.endsWith(".js") || path.endsWith(".css") || path.endsWith(".png") || path.endsWith(".ico"))
        server.sendHeader("Cache-Control", "max-age=86400");
      server.streamFile(file, getContentType(path));
      file.close();
      return;
    }
    if (path.startsWith("/api/")) {
      sendJson(404, "{\"error\":\"Unknown API endpoint. GET / for the full list.\"}");
    } else {
      sendJson(404, "{\"error\":\"File not found: " + escapeJson(path) + "\"}");
    }
  });

  // Don't delay(1) inside handleClient when idle — loop() spins freely, so new
  // connections get accepted sooner and animation frames never wait on the yield.
  server.enableDelay(false);
  server.begin();
  Serial.println("HTTP server started on port 80.");
  Serial.println("Test it: open http://" + WiFi.localIP().toString() + " in your browser.");

  // ── Auto-resume: restore the last display + brightness from NVS ──────────────
  // NOTE: WiFi may NOT be up here — waitForWiFiConnect gives up after 25s and we
  // run offline while the watchdog retries. Clock/calendar self-heal (SNTP syncs
  // once WiFi appears); weather retries on a short cadence until its first
  // successful fetch (see stepWeatherFrame).
  loadSettings();   // settings.ino — load persisted settings (merge-on-boot)

  // Brightness: restore the last committed value (this IS "default_brightness").
  brightness = prefs.getUChar("bri", brightness);
  resumeBri  = brightness;
  FastLED.setBrightness(brightness);

  // Boot display: a pinned boot_animation wins; otherwise fall back to auto-resume.
  if (settings.bootAnim.length()) {
    Serial.println("Boot: applying pinned boot animation: " + settings.bootAnim);
    applyAnimationBody("{\"type\":\"" + settings.bootAnim + "\"}");
  } else if (prefs.isKey("kind") && prefs.getString("kind", "") == "anim") {
    String body = prefs.isKey("animbody") ? prefs.getString("animbody", "") : "";
    if (body.length()) {
      Serial.println("Auto-resume: restoring last animation.");
      applyAnimationBody(body);   // defined in api_handlers.ino
    }
  }
}

// ============================================================
// SECTION 12: LOOP — runs continuously
//
// CRITICAL DESIGN RULE: Never use delay() in loop().
// delay() blocks the entire CPU — server.handleClient() can't
// run while we're waiting, so incoming HTTP requests time out.
//
// Instead we use millis() timestamps to check elapsed time:
//   if (now - lastFrameMs >= animationSpeed) { ...update frame... }
// This pattern is called "non-blocking timing" — it lets the loop
// run thousands of times per second, calling handleClient() every
// iteration, and only draws a new frame when enough time has passed.
// ============================================================

void loop() {
  // Loop-stall watchdog: track the longest gap between loop() iterations and
  // report it on the 10s heap line below. Anything over ~50ms is a visible
  // animation hitch (this instrumentation is how the blocking-CDC stall was
  // confirmed). A legit slow frame (weather fetch) also shows up here — honest.
  static uint32_t lastLoopIterMs = 0, loopMaxGapMs = 0;
  {
    uint32_t tIter = millis();
    if (lastLoopIterMs && tIter - lastLoopIterMs > loopMaxGapMs) loopMaxGapMs = tIter - lastLoopIterMs;
    lastLoopIterMs = tIter;
  }

  server.handleClient();   // process any pending HTTP requests first

  // WiFi self-heal backstop — deliberately GENTLE. The driver's autoReconnect
  // already retries every ~2s; this only kicks a wedged driver every 30s.
  // Don't make it aggressive: rapid forced auth cycling looks like an attack to
  // mesh-router security heuristics, which can blocklist the board's MAC (we
  // lived this — see PITFALLS, "mesh refused the 4-way handshake").
  static uint32_t lastWifiCheck = 0;
  if (millis() - lastWifiCheck >= 30000) {
    lastWifiCheck = millis();
    if (WiFi.status() != WL_CONNECTED) {
      Serial.printf("WiFi down (status=%d) — forcing reconnect.\n", (int)WiFi.status());
      WiFi.reconnect();
    }
  }

  // Heap monitor + low-heap safety. Both the weather and sketch deaths look like
  // heap exhaustion on this PSRAM-disabled board: a few requests' transient allocs
  // + WiFi buffers run the heap down until the server/WiFi can't allocate. Log the
  // trend; if free heap gets critically low, reboot to recover (auto-resume
  // restores the display) instead of hanging offline. Real fix: enable PSRAM.
  static uint32_t lastHeapLog = 0;
  if (millis() - lastHeapLog >= 10000) {
    lastHeapLog = millis();
    Serial.printf("[heap] free=%u largest-block=%u min-ever=%u max-stall=%lums\n",
                  ESP.getFreeHeap(), ESP.getMaxAllocHeap(), ESP.getMinFreeHeap(),
                  (unsigned long)loopMaxGapMs);
    loopMaxGapMs = 0;   // fresh window
    if (ESP.getFreeHeap() < 14000) {
      Serial.println("[heap] CRITICAL low heap — restarting to recover.");
      delay(50);
      ESP.restart();
    }
  }

  // Debounced auto-resume save: write to NVS once changes have settled (~8s),
  // instead of on every request — protects the WiFi creds in the same partition.
  if (resumeDirty && millis() - resumeDirtyMs >= 8000) {
    resumeDirty = false;
    prefs.putUChar("bri", resumeBri);   // last user-committed brightness, NOT the live global (grid-test sets that to 255)
    if (resumeKind.length()) prefs.putString("kind", resumeKind);
    if (resumeKind == "anim" && resumeBody.length()) prefs.putString("animbody", resumeBody);
    Serial.println("Auto-resume state saved to NVS.");
  }

  uint32_t now = millis();   // snapshot the clock once per loop iteration

  // Rainbow always at 66ms. Frostbite capped at 66ms minimum — shimmer and sine sparkles
  // need at least 15fps to look smooth; faster is fine, slower creates visible stepping.
  uint32_t effectiveRate = (animationName == "rainbow") ? 66u :
                           (animationName == "frostbite") ? min(animationSpeed, (uint32_t)66) :
                           animationSpeed;

  // Animation frame tick: only draw when enough time has elapsed
  if (animationActive && (now - lastFrameMs >= effectiveRate)) {
    lastFrameMs = now;
    if      (animationName == "fire")       stepFireFrame();
    else if (animationName == "rainbow")    runRainbowFrame();
    else if (animationName == "breathe")    runBreatheFrame();
    else if (animationName == "wave")       runWaveFrame();
    else if (animationName == "solid")      runSolidFrame();
    else if (animationName == "liquid")     stepLiquidFrame();
    else if (animationName == "imu")        stepImuFrame();
    else if (animationName == "chiptemp")   stepChipTempFrame();
    else if (animationName == "weather")    stepWeatherFrame();
    else if (animationName == "weather2")   stepWeather2Frame();
    else if (animationName == "timer_fill") stepTimerFillFrame();
    else if (animationName == "timer_snow") stepTimerSnowFrame();
    else if (animationName == "timer_text") stepTimerTextFrame();
    else if (animationName == "clock")      stepClockFrame();
    else if (animationName == "matrix_rain") stepMatrixFrame();
    else if (animationName == "snow")       stepSnowFrame();
    else if (animationName == "dancefloor") runDanceFloorFrame();
    else if (animationName == "spiral")    runSpiralFrame();
    else if (animationName == "starfield") runStarfieldFrame();
    else if (animationName == "fireworks")  stepFireworksFrame();
    else if (animationName == "fireworks2") stepFireworks2Frame();
    else if (animationName == "comet")      runCometFrame();
    else if (animationName == "claudesweep") stepClaudeSweepFrame();
    else if (animationName == "sun")       runSunFrame();
    else if (animationName == "frostbite") runFrostbiteFrame();
    else if (animationName == "calendar")  stepCalendarFrame();
    else if (animationName == "sound")     stepSoundFrame();
    else if (animationName == "presence")  runPresenceFrame();
    else if (animationName == "frames")    stepFramesFrame();
    matrixShow();
  }

  // Text scroll tick — same millis() pattern as animation above.
  // The text loops: scroll across, blank for 1 second, then restart.
  if (textActive) {
    if (scrollPausing) {
      // Blank screen pause between loops — wait for the timeout then restart
      if (now >= scrollPauseUntilMs) {
        scrollPausing = false;
        scrollOffset  = 0;
        lastScrollMs  = now;
        renderScrollFrame();
        matrixShow();
      }
    } else if (now - lastScrollMs >= scrollSpeed) {
      lastScrollMs = now;
      scrollOffset++;
      // Once the full text strip + the width of the screen has scrolled past,
      // the display is clear — start the 1-second pause before looping.
      if (scrollOffset >= MATRIX_W + scrollPixelLen) {
        scrollPausing      = true;
        scrollPauseUntilMs = now + 1000;
        fill_solid(leds, NUM_LEDS, CRGB::Black);
        matrixShow();
      } else {
        renderScrollFrame();
        matrixShow();
      }
    }
  }

  idleTick();   // idle_engine.ino — dead-man's switch screensaver
}
